version: '2.3'
services:
    sg_crnn_tensor:
        build: .
        runtime: nvidia
        stdin_open: true
        ports:
          - "8887:8887"
          - "6006:6006"
        volumes:
          - ../../data:/home/sg/data
          - ../scripts:/home/sg/scripts
          - ../outputs:/home/sg/outputs