version: '2.3'
services:
    sg_crnn_tensor:
        build: .
        runtime: nvidia
        stdin_open: true
        ports:
          - "8887:8887"
          - "6006:6006"
        volumes:
          - ../../../data:/home/od/data
          - ../scripts:/home/od/scripts
          - ../outputs:/home/od/outputs
